import { ItemType } from './ItemList';
import { v4 as uuidv4 } from 'uuid';

export const DataForList: ItemType[] = [
  { name: 'Liam', age: 25, city: 'New York', id: uuidv4() },
  { name: 'Olivia', age: 30, city: 'Los Angeles', id: uuidv4() },
  { name: 'Noah', age: 22, city: 'Chicago', id: uuidv4() },
  { name: 'Emma', age: 28, city: 'Houston', id: uuidv4() },
  { name: 'Oliver', age: 33, city: 'Phoenix', id: uuidv4() },
  { name: 'Ava', age: 24, city: 'Philadelphia', id: uuidv4() },
  { name: 'Elijah', age: 29, city: 'San Antonio', id: uuidv4() },
  { name: 'Sophia', age: 31, city: 'San Diego', id: uuidv4() },
  { name: 'James', age: 27, city: 'Dallas', id: uuidv4() },
  { name: 'Isabella', age: 26, city: 'San Jose', id: uuidv4() },
  { name: 'Jack', age: 21, city: 'New York', id: uuidv4() },
  { name: 'Charlotte', age: 34, city: 'Los Angeles', id: uuidv4() },
  { name: 'Mason', age: 32, city: 'Chicago', id: uuidv4() },
  { name: 'Amelia', age: 30, city: 'Houston', id: uuidv4() },
  { name: 'Ethan', age: 19, city: 'Phoenix', id: uuidv4() },
  { name: 'Mia', age: 23, city: 'Philadelphia', id: uuidv4() },
  { name: 'Henry', age: 28, city: 'San Antonio', id: uuidv4() },
  { name: 'Harper', age: 22, city: 'San Diego', id: uuidv4() },
  { name: 'Sebastian', age: 29, city: 'Dallas', id: uuidv4() },
  { name: 'Evelyn', age: 35, city: 'San Jose', id: uuidv4() },
  { name: 'Lucas', age: 26, city: 'New York', id: uuidv4() },
  { name: 'Ella', age: 21, city: 'Los Angeles', id: uuidv4() },
  { name: 'Alexander', age: 34, city: 'Chicago', id: uuidv4() },
  { name: 'Sofia', age: 31, city: 'Houston', id: uuidv4() },
  { name: 'William', age: 28, city: 'Phoenix', id: uuidv4() },
  { name: 'Avery', age: 24, city: 'Philadelphia', id: uuidv4() },
  { name: 'Benjamin', age: 30, city: 'San Antonio', id: uuidv4() },
  { name: 'Scarlett', age: 27, city: 'San Diego', id: uuidv4() },
  { name: 'Luca', age: 29, city: 'Dallas', id: uuidv4() },
  { name: 'Grace', age: 26, city: 'San Jose', id: uuidv4() },
  { name: 'Jayden', age: 22, city: 'New York', id: uuidv4() },
  { name: 'Zoe', age: 19, city: 'Los Angeles', id: uuidv4() },
  { name: 'Owen', age: 35, city: 'Chicago', id: uuidv4() },
  { name: 'Chloe', age: 23, city: 'Houston', id: uuidv4() },
  { name: 'Samuel', age: 27, city: 'Phoenix', id: uuidv4() },
  { name: 'Lily', age: 24, city: 'Philadelphia', id: uuidv4() },
  { name: 'Daniel', age: 33, city: 'San Antonio', id: uuidv4() },
  { name: 'Aria', age: 30, city: 'San Diego', id: uuidv4() },
  { name: 'Matthew', age: 29, city: 'Dallas', id: uuidv4() },
  { name: 'Emily', age: 25, city: 'San Jose', id: uuidv4() },
  { name: 'Caleb', age: 28, city: 'New York', id: uuidv4() },
  { name: 'Nora', age: 21, city: 'Los Angeles', id: uuidv4() },
  { name: 'Nathan', age: 26, city: 'Chicago', id: uuidv4() },
  { name: 'Mila', age: 24, city: 'Houston', id: uuidv4() },
  { name: 'Isaac', age: 30, city: 'Phoenix', id: uuidv4() },
  { name: 'Hannah', age: 22, city: 'Philadelphia', id: uuidv4() },
  { name: 'Henry', age: 19, city: 'San Antonio', id: uuidv4() },
  { name: 'Ella', age: 35, city: 'San Diego', id: uuidv4() },
  { name: 'David', age: 33, city: 'Dallas', id: uuidv4() },
  { name: 'Aurora', age: 26, city: 'San Jose', id: uuidv4() },
  { name: 'Levi', age: 21, city: 'New York', id: uuidv4() },
  { name: 'Victoria', age: 29, city: 'Los Angeles', id: uuidv4() },
  { name: 'Joseph', age: 24, city: 'Chicago', id: uuidv4() },
  { name: 'Addison', age: 35, city: 'Houston', id: uuidv4() },
  { name: 'Gabriel', age: 30, city: 'Phoenix', id: uuidv4() },
  { name: 'Brianna', age: 27, city: 'Philadelphia', id: uuidv4() },
  { name: 'Anthony', age: 28, city: 'San Antonio', id: uuidv4() },
  { name: 'Stella', age: 29, city: 'San Diego', id: uuidv4() },
  { name: 'Dylan', age: 19, city: 'Dallas', id: uuidv4() },
  { name: 'Lucy', age: 22, city: 'San Jose', id: uuidv4() },
  { name: 'Wyatt', age: 35, city: 'New York', id: uuidv4() },
  { name: 'Sadie', age: 26, city: 'Los Angeles', id: uuidv4() },
  { name: 'Jonathan', age: 31, city: 'Chicago', id: uuidv4() },
  { name: 'Clara', age: 23, city: 'Houston', id: uuidv4() },
  { name: 'Aaron', age: 24, city: 'Phoenix', id: uuidv4() },
  { name: 'Samantha', age: 28, city: 'Philadelphia', id: uuidv4() },
  { name: 'Carter', age: 29, city: 'San Antonio', id: uuidv4() },
  { name: 'Rose', age: 30, city: 'San Diego', id: uuidv4() },
  { name: 'Charles', age: 22, city: 'Dallas', id: uuidv4() },
  { name: 'Ariana', age: 26, city: 'San Jose', id: uuidv4() },
];
